DjangoBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^manager/', include(admin.site.urls)),
    url(r'^favicon.ico$', RedirectView.as_view(url=r'static/images/favicon.ico')),
    url(r'^ads.txt$', RedirectView.as_view(url=r'static/ads/ads.txt')),
    url(r'^bdunion.txt$', RedirectView.as_view(url=r'static/ads/bdunion.txt')),
    url(r'^search/', include('haystack.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [
    url(r'^$', views.index_page, name='index_page'),  # 首页
    url(r'^articles', views.article_list, name='article_list'),  # 文章列表页（支持分页、按分类、按标签）
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_detail, name='article_detail'),  # 文章详情
    url(r'^categories', views.category_list, name='category_list'),  # 所有分类页
    url(r'^tags', views.tag_list, name='tag_list'),  # 所有标签
    url(r'^about', views.about_page, name='about_page'),  # 关于 页面
    url(r'^submit_comment', views.submit_comment, name='submit_comment'),  # 提交评论

    url(r'^editor/article', views.admin_edit_article, name='admin_edit_article'),  # 管理后台编写文章
    url(r'^editor/save', views.admin_edit_save, name='admin_edit_save'),  # 异步保存文章
    url(r'^editor/image_upload', views.admin_image_upload, name='admin_image_upload'),  # 上传图片

    url(r'^bark', views.bark, name='bark'),  # 个人小需求，给bark发消息，可忽略此项
]

blog/models.py
import uuid
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField('分类名称', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '文章分类'
        verbose_name_plural = '文章分类'


class Tag(models.Model):
    name = models.CharField('标签名称', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'


def random_img_name(instance, filename):
    return 'micro_images/{0}.{1}'.format(str(uuid.uuid1()), filename.split('.')[-1])


def random_music_name(instance, filename):
    return 'music_attach/{0}.{1}'.format(str(uuid.uuid1()), filename.split('.')[-1])


class Article(models.Model):
    STATUS_CHOICES = (
        (0, '草稿'),
        (1, '公开发布')
    )
    PIN_CHOICES = {
        (0, '非置顶'),
        (1, '置顶')
    }
    YES_NO_CHOICES = (
        (0, '否'),
        (1, '是')
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='所属分类', null=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='标签', null=True, blank=True)
    title = models.CharField('标题', max_length=200)
    description = models.CharField('摘要', max_length=500, null=True, blank=True)
    text = models.TextField('正文', help_text='长文请使用markdown编辑器编辑，短微博可直接在此处后台编辑。')
    time = models.DateTimeField('发布时间')
    pin = models.IntegerField('是否置顶', choices=PIN_CHOICES, default=0)
    status = models.IntegerField('状态', choices=STATUS_CHOICES, default=1)
    pwd = models.CharField('访问密码', max_length=50, null=True, blank=True)
    is_micro = models.IntegerField('是否微博', choices=YES_NO_CHOICES, default=0)
    micro_picture = models.ImageField('微博附图', upload_to=random_img_name, null=True, blank=True)
    music_file = models.FileField('背景音乐', upload_to=random_music_name, null=True, blank=True)

    def get_micro_text_html(self):
        return self.text.replace('\n', '<br/>')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'


class Comment(models.Model):
    STATUS_CHOICES = (
        (-1, '屏蔽'),
        (0, '公开展示'),
        (1, '置顶展示')
    )
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='所属文章')
    user = models.CharField('评论者昵称', max_length=100, default='匿名用户')
    email = models.CharField('评论者邮箱', max_length=100, default='未提供')
    text = models.TextField('内容')
    time = models.DateTimeField('发布时间', auto_now_add=True)
    status = models.IntegerField('状态', choices=STATUS_CHOICES, default=0)

    def __str__(self):
        return self.user + ' - ' + self.article.title

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'


class Attachment(models.Model):
    content = models.FileField(upload_to='attachments/%Y/%m/')

    def __str__(self):
        return '文件-%d' % self.id

    class Meta:
        verbose_name = '附件'
        verbose_name_plural = '附件'


class Counter(models.Model):
    key = models.CharField('Key', max_length=100, primary_key=True)
    value = models.IntegerField('计数', default=0)

    def __str__(self):
        return '%s - %d' % (self.key, self.value)

    class Meta:
        verbose_name = '计数器'
        verbose_name_plural = '计数器'

blog/views.py
import json
import os

import uuid

import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from . import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def _get_counter(key, increase=True):
    counters = models.Counter.objects.filter(key=key)
    if len(counters) == 1:
        counter = counters[0]
    else:
        counter = models.Counter()
        counter.key = key
        counter.save()
    if increase:
        counter.value += 1
        counter.save()
    return counter.value


# Create your views here.
def index_page(req):
    pin_articles = models.Article.objects.filter(status=1, pin=1).order_by('-time')
    recent_articles = models.Article.objects.filter(status=1).order_by('-time')[:10]
    raw_categories = models.Category.objects.all()
    categories = []
    for ct in raw_categories:
        categories.append({
            'category': ct,
            'article_count': ct.article_set.count(),
        })
    categories = sorted(categories, key=lambda x: x['article_count'], reverse=True)
    tags = models.Tag.objects.all()
    context = {
        'pin_articles': pin_articles,
        'recent_articles': recent_articles,
        'categories': categories,
        'tags': tags,
        'site_counter': _get_counter('site_total'),  # 全站计数
    }
    return render(req, 'blog/index.html', context=context)


def article_list(req):
    category = req.GET.get('category', None)
    tag = req.GET.get('tag', None)
    page = req.GET.get('page', '1')
    filter_string = ''
    if category:
        articles = models.Article.objects.filter(status=1, category=int(category)).order_by('-time')
        filter_string = 'category=' + category
    elif tag:
        articles = models.Article.objects.filter(status=1, tags=int(tag)).order_by('-time')
        filter_string = 'tag=' + tag
    else:
        articles = models.Article.objects.filter(status=1).order_by('-time')
    paginator = Paginator(articles, 10)  # 每页 10 篇文章
    try:
        ok_articles = paginator.page(int(page))
    except:
        ok_articles = paginator.page(1)
    context = {
        'articles': ok_articles,
        'filter_string': filter_string,
        'site_counter': _get_counter('site_total'),  # 全站计数
    }
    return render(req, 'blog/article_list.html', context=context)


def article_detail(req, article_id):
    if req.method == 'GET':
        article = models.Article.objects.filter(id=int(article_id))[0]
        if not article.pwd:
            # 无需密码，直接访问
            pinned_comments = models.Comment.objects.filter(article=article, status=1).order_by('-time')
            normal_comments = models.Comment.objects.filter(article=article, status=0).order_by('-time')
            context = {
                'article': article,
                'pinned_comments': pinned_comments,
                'normal_comments': normal_comments,
                'site_counter': _get_counter('site_total'),  # 全站计数
                'article_view_counter': _get_counter('article_view_%d' % article.id),  # 文章访问计数
            }
            return render(req, 'blog/article_detail.html', context=context)
        else:
            # 需要密码访问，跳转密码输入页
            context = {
                'article': article,
                'msg': '文章内容已加密，请输入访问密码。',
                'site_counter': _get_counter('site_total', increase=False),  # 全站计数
                'article_view_counter': _get_counter('article_view_%d' % article.id, increase=False),  # 文章访问计数
            }
            return render(req, 'blog/article_detail_encrypted.html', context=context)
    else:
        article = models.Article.objects.filter(id=int(article_id))[0]
        pwd = req.POST.get('pwd', None)
        if pwd and pwd == article.pwd:
            pinned_comments = models.Comment.objects.filter(article=article, status=1).order_by('-time')
            normal_comments = models.Comment.objects.filter(article=article, status=0).order_by('-time')
            context = {
                'article': article,
                'pinned_comments': pinned_comments,
                'normal_comments': normal_comments,
                'site_counter': _get_counter('site_total'),  # 全站计数
                'article_view_counter': _get_counter('article_view_%d' % article.id),  # 文章访问计数
            }
            return render(req, 'blog/article_detail.html', context=context)
        else:
            context = {
                'article': article,
                'msg': '密码错误，请重试。',
            }
            return render(req, 'blog/article_detail_encrypted.html', context=context)


def category_list(req):
    raw_categories = models.Category.objects.all()
    categories = []
    for ct in raw_categories:
        categories.append({
            'category': ct,
            'article_count': ct.article_set.count(),
        })
    categories = sorted(categories, key=lambda x: x['article_count'], reverse=True)
    context = {
        'categories': categories,
        'site_counter': _get_counter('site_total'),  # 全站计数
    }
    return render(req, 'blog/category_list.html', context=context)


def tag_list(req):
    tags = models.Tag.objects.all()
    context = {
        'tags': tags,
        'site_counter': _get_counter('site_total'),  # 全站计数
    }
    return render(req, 'blog/tag_list.html', context=context)


def about_page(req):
    context = {
        'site_counter': _get_counter('site_total'),  # 全站计数
    }
    return render(req, 'blog/about.html', context=context)


def submit_comment(req):
    comment = models.Comment()
    user = req.POST.get('nickName', None)
    email = req.POST.get('email', None)
    text = req.POST.get('content', None)
    article_id = req.POST.get('aid', '-1')
    article = models.Article.objects.filter(id=int(article_id))
    if text and len(article) == 1:
        article = article[0]
        if not user.strip():
            user = '匿名用户'
        if not email.strip():
            email = '未提供'
        comment.user = user
        comment.email = email
        comment.text = text
        comment.article = article
        comment.save()
    return redirect('/article/' + article_id)


@login_required(login_url='/manager/login/')
def admin_edit_article(req):
    article_id = req.GET['id']
    article = models.Article.objects.filter(id=int(article_id))
    if len(article) != 1:
        return HttpResponse('参数错误，未找到这篇文章。')
    article = article[0]
    context = {
        'article': article
    }
    return render(req, 'blog/admin/editor.html', context=context)


@csrf_exempt
@login_required(login_url='/manager/login/')
def admin_edit_save(req):
    data = req.POST.get('editormd-markdown-doc', None)
    article_id = req.POST.get('id', None)
    if id and data:
        article = models.Article.objects.filter(id=int(article_id))
        if len(article) == 1:
            article = article[0]
            article.text = data
            article.save()
            msg = '保存成功。'
        else:
            msg = '文章id错误，保存失败。'
    else:
        msg = '数据格式错误，保存失败。'
    result = {
        'status': msg,
    }
    return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required(login_url='/manager/login/')
def admin_image_upload(req):
    data = req.FILES.get('editormd-image-file', None)
    if data:
        extension = os.path.splitext(data.name)[-1]
        file_name = str(uuid.uuid1())
        with open(os.path.join(settings.BASE_DIR, 'uploads', 'images', file_name) + extension, 'wb+') as destination:
            for chunk in data.chunks():
                destination.write(chunk)
        result = {
            'success': 1,
            'message': '上传成功。',
            'url': '/uploads/images/' + file_name + extension,
        }
    else:
        result = {
            'success': 0,
            'message': '上传失败，请重试。',
            'url': '/',
        }
    return HttpResponse(json.dumps(result), content_type='application/json')


# 个人小需求，给bark发消息，可忽略此项
def bark(req):
    content = req.GET.get('content', None)
    ret = {
        'status': 'ok'
    }
    if not content:
        return HttpResponse(json.dumps(ret), content_type='application/json')
    url = 'https://api.day.app/LyG8H2uEhfs9EHYXpZzsT8/%s' % content
    r = requests.get(url)
    return HttpResponse(json.dumps(ret), content_type='application/json')

templates/blog/article_detail_encrypted.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
      {% include 'blog/includes/head.html' %}
      <title>{{article.title}} - Articles - Coding Cat</title>
      <style>
          #renderMd h1{
              font-size: 1.6rem;
          }
          #renderMd h2{
              font-size: 1.4rem;
          }
          #renderMd h3{
              font-size: 1.2rem;
          }
          #renderMd h4{
              font-size: 1.1rem;
          }
          #renderMd h5{
              font-size: 1rem;
          }
          #renderMd h6{
              font-size: 0.9rem;
          }
          #renderMd img{
              max-width: 95%;
              margin: 10px;
              border: 1px solid #d3d3d3;
          }
      </style>
  </head>
 <body>

    {% include 'blog/includes/nav.html' %}

     <br/>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">

          <div class="blog-post">
            <h3>{{article.title}}</h3>
            <p class="blog-post-meta">
                {{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}
                &nbsp;&nbsp;&nbsp;&nbsp;
                | &nbsp;&nbsp;&nbsp;&nbsp;
                {{ article_view_counter }} Views
            </p>
            <p class="bg-light shadow" style="padding:1rem;">
                {{article.description}}
            </p>
            <br/>
            <div id="renderMd">
                <form action="{% url 'blog:article_detail' article.id %}" method="post">
                    {%csrf_token%}
                  <div class="form-group">
                    <label for="pwd">{{msg}}</label>
                    <input type="text" class="form-control" required id="pwd" name="pwd" placeholder="Password">
                  </div>
                  <button type="submit" class="btn btn-primary"> Submit </button>
                </form>
            </div>
          </div><!-- /.blog-post -->

            <br/><br/>
            <hr/>
            <br/>


        </div><!-- /.blog-main -->
<!--

        <aside class="col-md-4 blog-sidebar">

          <div class="p-3 mb-3 bg-light rounded">
            <h5 class="">目录</h5>
            <p class="mb-0">to be added...</p>

          </div>


        </aside>&lt;!&ndash; /.blog-sidebar &ndash;&gt;
-->

      </div><!-- /.row -->

    </main><!-- /.container -->


 {% include 'blog/includes/footer.html' %}


</body>
</html>

templates/blog/article_list.html
{% load static %}

<!DOCTYPE html>


<html>
  <head>
      {% include 'blog/includes/head.html' %}
      <title>Articles - Coding Cat</title>
  </head>
 <div>

    {% include 'blog/includes/nav.html' %}


    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h5 class="pb-3 mb-4 border-bottom">
            Articles
          </h5>

        {% for article in articles.object_list %}
          <div class="blog-post">
             {% if article.is_micro == 0 %}
                <a href="{% url 'blog:article_detail' article.id %}"><h5>{{article.title}}</h5></a>
                <p class="blog-post-meta">{{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}</p>
                <p>{{article.description}}</p>
              {% else %}
                <h5>{{article.title}}</h5>
                <p class="blog-post-meta">MicroBlog | {{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}</p>
                  {% if article.micro_picture %}
                      <p class="blog-micro-img"><img src="/uploads/{{ article.micro_picture.name }}"></p>
                  {% endif %}
                <p>{{article.get_micro_text_html|safe}}<br/><br/></p>
          {% endif %}
            <hr>
          </div><!-- /.blog-post -->
        {% empty %}
            Nothing here.<br/>
        {% endfor %}

        {% if articles.object_list %}
            <br/><br/>
         <nav aria-label="Page navigation example">
          <ul class="pagination">
              {% if articles.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:article_list' %}?page={{articles.previous_page_number}}&{{filter_string}}">Previous</a></li>
              {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
              {% endif %}

              <li class="page-item"><a class="page-link" style="color:black;" href="#"> {{articles.number}} of {{articles.paginator.num_pages}} </a></li>

            {% if articles.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'blog:article_list' %}?page={{articles.next_page_number}}&{{filter_string}}">Next</a></li>
              {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
              {% endif %}
          </ul>
        </nav>

          {% endif %}

        </div><!-- /.blog-main -->


        <aside class="col-md-4 blog-sidebar">

          {% include 'blog/includes/ad_square.html' %}


        </aside>


      </div><!-- /.row -->

    </main><!-- /.container -->


 {% include 'blog/includes/footer.html' %}
    

</body>
</html>

templates/blog/category_list.html
{% load static %}

<!DOCTYPE html>


<html>
  <head>
      {% include 'blog/includes/head.html' %}
      <title>Categories - Coding Cat</title>
  </head>
 <div>

    {% include 'blog/includes/nav.html' %}


    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h5 class="pb-3 mb-4">
            All Categories
          </h5>

        <ul class="list-group list-group-flush">
          {% for it in categories %}
            <li class="list-group-item">
                <a href="{% url 'blog:article_list' %}?category={{it.category.id}}">
                    {{it.category.name}}
                    <span class="badge badge-primary badge-pill float-right">{{it.article_count}}</span>
                </a>
            </li>
          {% empty %}
          哎呀，还没有分类。
          {% endfor %}
        </ul>


        </div><!-- /.blog-main -->

        <!--<aside class="col-md-4 blog-sidebar">-->

          <!--<div class="p-3 mb-3 bg-light rounded">-->
            <!--<h5 class="">Timeline</h5>-->
            <!--<p class="mb-0">2018年8月</p>-->
            <!--<p class="mb-0">2018年7月</p>-->
            <!--<p class="mb-0">2018年6月</p>-->
            <!--<p class="mb-0">2018年5月</p>-->
          <!--</div>-->


        <!--</aside>&lt;!&ndash; /.blog-sidebar &ndash;&gt;-->

      </div><!-- /.row -->

    </main><!-- /.container -->


 {% include 'blog/includes/footer.html' %}
    

</body>
</html>

templates/blog/include_head.html
{% load static %}

<!--
Hey!
 (๑•̀ㅂ•́)و✧

说吧，打开控制台想干啥？

-->

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="辛东兴的个人博客网站，分享技术、技能、实用工具，还有其他好玩的东西。">
<meta name="keywords" content="辛东兴,中国人民大学,人工智能,机器学习,自然语言处理，NLP,深度学习,分享,技术,技能,实用工具,一只技术宅,微信公众号">
<meta name="author" content="辛东兴">

<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'css/custom_font.css' %}" rel="stylesheet">
<link href="{% static 'css/blog.css' %}" rel="stylesheet">

templates/blog/include_nav.html
{% load static %}

<!-- 关注公众号 -->
    <div class="modal fade" id="wechatModal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">微信扫一扫 订阅最新动态</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img src="{% static 'images/qrcode.png' %}" style="max-width:100%;"/>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
        <br/>
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="/">你竟然在代码里下毒</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="/">首页 </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:article_list' %}">文章</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:category_list'%}">分类</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:tag_list' %}">标签</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:about_page' %}">关于</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="关键词" aria-label="Search">
              <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">搜索</button>
            </form>
          </div>
        </nav>
    </div>

<br/>

templates/blog/index.html
{% load static %}

<!DOCTYPE html>


<html>
  <head>
      {% include 'blog/includes/head.html' %}
      <title>Home - Coding Cat</title>
      <link href="{% static 'css/jqcloud.min.css' %}" rel="stylesheet">

  </head>

 <div>

    {% include 'blog/includes/nav.html' %}

    <div class="container">
        <hr/><br/>
        <h5 class="pb-3">
           Pinned Items
          </h5>
      <div class="index-card card-group">
          <div class="card">
              <div class="card-body">
                <h5 class="card-title">Ataraxia New Tab</h5>
                <h6 class="card-subtitle mb-2 text-muted">Chrome New Tab Extension </h6>
                <p class="card-text">Chrome 新标签页插件，自动同步 Bing 每日壁纸。</p>
                <a href="/ataraxia/" class="card-link">Download</a>
                <a href="https://github.com/bytetopia/Chrome-New-Tab-with-Bing-Wallpaper" class="card-link">Source Code</a>
              </div>
          </div>
          <div class="card">
              <div class="card-body">
                <h5 class="card-title">Github</h5>
                <h6 class="card-subtitle mb-2 text-muted">Open Source </h6>
                <p class="card-text">博客文章、开源仓库。</p>
                <a href="https://github.com/bytetopia" class="card-link">View Github</a>
              </div>
          </div>
      </div>
    </div>



    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h5 class="pb-3 mb-4 border-bottom">
              Recent Posts
          </h5>

        {% for article in pin_articles %}
          <div class="blog-post">
          {% if article.is_micro == 0 %}
            <a href="{% url 'blog:article_detail' article.id %}"><h5>{{article.title}}</h5></a>
            <p class="blog-post-meta"><span class="badge badge-primary">Pinned</span> {{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}</p>
            <p>{{article.description}}</p>
          {% else %}
            <h5>{{article.title}}</h5>
            <p class="blog-post-meta"><span class="badge badge-secondary">Pinned</span> {{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}</p>
              {% if article.micro_picture %}
                  <p><img src="/uploads/micro_images/{{ article.micro_picture.name }}"></p>
              {% endif %}
            <p>{{article.get_micro_text_html|safe}}<br/><br/></p>
          {% endif %}
            <hr>
          </div><!-- /.blog-post -->
        {% endfor %}

        {% for article in recent_articles %}
          <div class="blog-post">
           {% if article.is_micro == 0 %}
            <a href="{% url 'blog:article_detail' article.id %}"><h5>{{article.title}}</h5></a>
            <p class="blog-post-meta">{{article.time|date:'M d'}}&nbsp;&nbsp;{{article.time|date:'Y'}}</p>
            <p>{{article.description}}</p>
          {% else %}
            <h5>{{article.title}}</h5>
            <p class="blog-post-meta"><span class="badge badge-secondary">MicroBlog</span> {{article.time}}</p>
              {% if article.micro_picture %}
                  <p class="blog-micro-img"><img src="/uploads/{{ article.micro_picture.name }}"></p>
              {% endif %}
            <p>{{article.get_micro_text_html|safe}}<br/><br/></p>
          {% endif %}
            <hr>
          </div><!-- /.blog-post -->
        {% endfor %}



         <nav class="blog-pagination">
            <a class="btn btn-outline-secondary" href="{% url 'blog:article_list' %}">View More</a>
          </nav>

          <div>
            {% include 'blog/includes/ad_bar.html' %} 
          </div>

        </div><!-- /.blog-main -->

        <aside class="col-md-4 blog-sidebar">

          <div class="p-3 mb-3 bg-light rounded">
            <h5 class="">Tags</h5>
            <div id="cloud" style="min-height:150px;width:100%;">
            </div>
          </div>

          <div class="p-3 mb-3 bg-light rounded">
            <h5 class="">Categories</h5>
            <ul class="list-group list-group-flush">
              {% for ct in categories %}
                <li class="list-group-item" style="background-color:#F8F9FA;">
                    <a href="{% url 'blog:article_list' %}?category={{ct.category.id}}">
                        {{ct.category.name}}
                        <span class="badge badge-primary badge-pill float-right">{{ct.article_count}}</span>
                    </a>
                </li>
              {% empty %}
              Nothing here.
              {% endfor %}
            </ul>

          </div>

          {% include 'blog/includes/ad_square.html' %}
          {% include 'blog/includes/aside_wechat.html' %}
          {% include 'blog/includes/aside_links.html' %}
          {% include 'blog/includes/ad_square.html' %}


        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </main><!-- /.container -->


 {% include 'blog/includes/footer.html' %}

     <script src="{% static 'js/jqcloud.min.js' %}"></script>
     <script>
         var words = [
             {% for tag in tags %}
              {text: "{{tag.name}}", weight: {{tag.article_set.count}}, link: "{% url 'blog:article_list'%}?tag={{tag.id}}"},
             {% endfor %}
            ];

            $('#cloud').jQCloud(words, {
              shape: 'rectangular'
            });
     </script>
    

</body>
</html>